### ISSUE TITLE
Eq (2) and (3)

### ISSUE THREAD

**Issue by Lilyo** [kahnchana/opl#1]
Hi, thanks to your great work first! I curious about that do you need to average the s and d in eq2 and eq3 respectively? Because you take “mean operator” in your pseudo code but “sum operation” in equation.

**Comment by kahnchana** [comment]
Hi thanks a lot for pointing this out. In the implementation we use the mean operator (divide each sum by the count of positive / negative pairs in batch) because it leads to more stable training. I do realise we've omitted this term in our equations. I will work on modifying the equations once we revise this paper.
